import CategoryList from "@/components/ui/CategoryList/CategoryList";
import Navbar from "@/components/ui/Navbar/Navbar";
import Sidebar from "@/components/ui/Sidebar/Sidebar";
import { Inter } from "next/font/google";

import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "./nextToast";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} font-Inter font-medium text-[#4D4D4D] bg-[#EBEEF2] mt-10 mx-10   `}
    >
      <body className="">
        <div className="flex gap-7 ">
          <div>
            <Sidebar></Sidebar>
          </div>

          <div className="flex-1 ">
            <div className="mb-5">
              <Navbar></Navbar>
            </div>
            <div className="flex ">
              <div className="w-[21%] h-full mr-5">
                <CategoryList></CategoryList>
              </div>

              <div className="scroll-smooth w-[62%] pr-2 overflow-y-auto h-[835px]">
                {children}
              </div>

              <div className="bg-[#FFFFFF] ml-2 w-[17%]">right side bar</div>
            </div>
          </div>
        </div>
        <ToastContainer position="bottom-center" />
      </body>
    </html>
  );
}
