import CategoryList from "@/components/ui/CategoryList/CategoryList";
import Navbar from "@/components/ui/Navbar/Navbar";
import Settings from "@/components/ui/Settings";
import Sidebar from "@/components/ui/Sidebar/Sidebar";
import { Inter } from "next/font/google";
import Image from "next/image";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "../components/ui/nextToast";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

import BackPage from "@/components/ui/BackPage/BackPage";
import SmallCategories from "@/components/ui/SmallCategories/SmallCategories";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export default function RootLayout({ children }) {
  const url = [
    { img: "https://duaruqyah.com/assets/nav/home.svg", id: 1 },
    { img: "https://duaruqyah.com/assets/nav/alldua.svg", id: 2 },
    { img: "https://duaruqyah.com/assets/nav/memorize.svg", id: 3 },
    { img: "https://duaruqyah.com/assets/nav/bookmark.svg", id: 4 },
    { img: "https://duaruqyah.com/assets/nav/ruqyah.svg", id: 5 },
  ];

  return (
    <html
      lang="en"
      className={`${inter.variable}  font-Inter font-medium text-[#4D4D4D] bg-[#EBEEF2] lg:mt-10 ml-3 mr-2 lg:mx-10 md:mt-0  mt-4`}
    >
      <body className="">
        <div className="flex gap-7 ">
          <div className="hidden lg:block">
            <Sidebar></Sidebar>
          </div>

          <div className="flex-1 ">
            <div className="mb-5 hidden  lg:block md:hidden ">
              <Navbar></Navbar>
            </div>
            <div className="mb-5 hidden md:block lg:hidden fixed w-full shadow-sm z-30">
              <Navbar></Navbar>
            </div>

            <div className="flex lg:hidden md:hidden items-center justify-between">
              <div className="flex items-center gap-3">
                <BackPage></BackPage>{" "}
                <h2 className="font-normal text-lg">Duas Page</h2>
              </div>
              <div>
                <Link href="/settings">
                  <Image
                    src={`https://duaruqyah.com/assets/tab/home/settings.svg`}
                    width={25}
                    height={25}
                    alt="dua"
                  ></Image>
                </Link>
              </div>
            </div>

            <div className="lg:hidden  block ">
              <SmallCategories></SmallCategories>
            </div>
            <div className="lg:flex">
              <div className="w-[21%] h-full mr-5 lg:block hidden">
                <CategoryList></CategoryList>
              </div>

              <div className="scroll-smooth lg:w-[62%] lg:pr-2  lg:overflow-y-scroll  lg:h-[835px] ">
                {children}
              </div>

              <div className="lg:block hidden bg-[#FFFFFF] ml-2 w-[18%]  h-[810px] rounded-3xl">
                <Settings></Settings>
              </div>
            </div>
            <div className="bg-[#ffffff]  lg:hidden block fixed rounded-t-[50px] bottom-0  w-full -mx-3 shadow-xl  z-30">
              <div className="flex justify-between mx-5 ">
                {url.map((item) => (
                  <div
                    key={item.id}
                    className="md:my-6 my-5 bg-[#F7F8FA]   p-2 rounded-full cursor-pointer hover:scale-105 "
                  >
                    {" "}
                    <Image
                      src={item.img}
                      width={20}
                      height={20}
                      alt="dua"
                    ></Image>{" "}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
        <ToastContainer position="bottom-center" />
      </body>
    </html>
  );
}
